/* Generated By:JavaCC: Do not edit this line. ExpressionParserConstants.java */
package com.ogprover.pp.tp.expressions.parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SEGMENT = 5;
  /** RegularExpression Id. */
  int AREA = 6;
  /** RegularExpression Id. */
  int SQUARE = 7;
  /** RegularExpression Id. */
  int PLUS = 8;
  /** RegularExpression Id. */
  int MINUS = 9;
  /** RegularExpression Id. */
  int MULTIPLY = 10;
  /** RegularExpression Id. */
  int DIVIDE = 11;
  /** RegularExpression Id. */
  int NUMBER = 12;
  /** RegularExpression Id. */
  int DIGIT = 13;
  /** RegularExpression Id. */
  int LABEL = 14;
  /** RegularExpression Id. */
  int INDEX = 15;
  /** RegularExpression Id. */
  int LETTER = 16;
  /** RegularExpression Id. */
  int CHAR = 17;
  /** RegularExpression Id. */
  int LEFTPAR = 18;
  /** RegularExpression Id. */
  int RIGHTPAR = 19;
  /** RegularExpression Id. */
  int LEFTBRACKET = 20;
  /** RegularExpression Id. */
  int RIGHTBRACKET = 21;
  /** RegularExpression Id. */
  int COMMA = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Segment\"",
    "\"Area\"",
    "<SQUARE>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<NUMBER>",
    "<DIGIT>",
    "<LABEL>",
    "<INDEX>",
    "<LETTER>",
    "<CHAR>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
  };

}
